language: java
jdk:
  - oraclejdk6

install:
  - ./gradlew --refresh-dependencies --stacktrace

script:
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport coveralls

after_failure:
  - "cat ./build/test-results/*.xml"
